# Makefile for the quectel drivers.
#
# 1 Jan 2018, Gale
# 

#obj-$(CONFIG_LOW_POWER_CONSUME_V2)  += low_power_consume_driver_v2/
obj-y	  += ql_lpm/
obj-$(CONFIG_QL_SECURITY) += security/
obj-$(CONFIG_QTZONE)	  += qtzone/
obj-$(CONFIG_QSTART)	  += qstart/
obj-$(CONFIG_QABSYSTEM)   += qabsystem/
